services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile # Main Service
    ports:
      - "8000:8000"
    volumes:
      - ../data/:/app/data/ # Mount the data
    environment:
      - DATABASE_URL=sqlite:///data/orders.db

  streamlit:
    build:
      context: ../streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
